version: "3.7"

services:
    
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: owntone
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/owntone:/etc/owntone
      - ${APP_DATA_DIR}/data/media:/srv/media
      - ${APP_DATA_DIR}/data/cache:/var/cache/owntone
    restart: unless-stopped