version: "3.7"

services:
    
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: owntone
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ./avahi-daemon:/etc/init.d/avahi-daemon
      - ${APP_DATA_DIR}/data/owntone:/etc/owntone
      - ${APP_DATA_DIR}/data/media:/srv/media
      - ${APP_DATA_DIR}/data/cache:/var/cache/owntone
    restart: unless-stopped