version: "3.7"

services:
    
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: owntone
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped