version: "3.7"

services:
  # app_proxy:
  #   environment:
  #     APP_HOST: frida-actual_server_1
  #     APP_PORT: 5006
  #     PROXY_AUTH_ADD: "false"

  server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    user: 1000:1000
    ports:
      - 5006:5006
    environment:
      - ACTUAL_PORT=5006
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: unless-stopped
